
spring:
  datasource:
    username: root
    password: 111111
    url: 'jdbc:mysql://192.168.2.62:3306/hyjinfu.order?useLegacyDatetimeCode=false&serverTimezone=Asia/Hong_Kong&useSSL=false'
  cloud:
    loadbalancer:
      retry:
        enabled: true
  zipkin:
    base-url: 'http://zipkin_server:9411/'
encrypt:
  key: '*&3loa#@9no_0*(!'
mybatis:
  mapper-locations: 'classpath:mapper/*Mapper.xml'
  type-aliases-package: 'com.hyjinfu.orderServer.domain'
flyway:
  baseline-on-migrate: true
