spring:
  application:
    name: account
  datasource:
    username: root
    password: 111111
    url: 'jdbc:mysql://localhost:3306/hyjinfu.account?useLegacyDatetimeCode=false&serverTimezone=Asia/Hong_Kong&useSSL=false'
#  rabbitmq:
#    host: rabbitmq
#    username: chris
#    password: 123123
#    virtual-host: prontera
#    listener:
#      retry:
#        enabled: true
#    template:
#      retry:
#        enabled: true
#      mandatory: true
#    publisher-returns: true
#    publisher-confirms: true
  cloud:
    loadbalancer:
      retry:
        enabled: true
#    config:
#      discovery:
#        enabled: true
#        service-id: 'config-server'
#      fail-fast: true
  zipkin:
    base-url: 'http://zipkin_server:9411/'
